# Generated by Django 5.0.3 on 2024-04-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('tax_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unity', models.CharField(max_length=10)),
                ('price_indiv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('sujet', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('characteristic', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.commande')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='id_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.produit'),
        ),
    ]
