# Generated by Django 5.0.3 on 2024-04-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_fournisseur_identificateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='type',
        ),
    ]
