# Generated by Django 5.0.3 on 2024-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_commande_price_indiv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='date',
            field=models.CharField(max_length=15),
        ),
    ]
