# Generated by Django 5.0.3 on 2024-04-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_boncommande_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
