# Generated by Django 5.0.3 on 2024-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_boncommande_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='consultation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
