# Generated by Django 5.0.3 on 2024-04-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_fournisseur_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.client'),
        ),
    ]
