# Generated by Django 5.0.3 on 2024-06-02 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_userstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='characteristic',
        ),
        migrations.AlterField(
            model_name='produit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='website.produit')),
            ],
        ),
    ]
