# Generated by Django 5.0.3 on 2024-06-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_produit_characteristic_alter_produit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='characteristic',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
